#!/bin/bash

if [ $# -eq 0 ]; then
    echo "No arguments supplied"
    exit 1
fi

test=$1
cd ~/cs350-os161/root
for i in {1..100}
do  
    sys161 kernel-ASST${1} "p testbin/sty;q";done > ../testOut
    #n > testOut
    #echo "Run:" ${i} ${test}
    #echo ${test}\n"q"\n | ./run 2 > testOut
    #echo -e ${test}"\nq"
    #echo -e ${test}"\nq" | ./run 2
done

