#!/bin/bash

if [ $# -eq 0 ]; then
    echo "No arguments supplied"
    exit 1
fi

test=$1

for i in {1..3}
do
    echo "Run:" ${i} ${test}
    echo ${test}\n"q"\n | ./run 2 > testOut
    #echo -e ${test}"\nq"
    #echo -e ${test}"\nq" | ./run 2
done

