#!/bin/bash

if [ $# -eq 0 ]; then
    echo "No arguments supplied"
    exit 1
fi

test=$1

for i in {1..3}
do
    echo "Run:" ${i} ${test}
    echo -e ${test}"\nq"
    echo -e ${test}"\nq" | ./run 2
done

#need to add output comparison (test dependent)