#!/bin/bash

if [ $# -eq 0 ]; then
    echo "No arguments supplied"
    exit 1
elif [ $# -eq 2 ]; then
    echo "Running w/ Debugger"
    cd ~/cs350-os161/root
    sys161 -w kernel-ASST$1
else
    cd ~/cs350-os161/root
    sys161 kernel-ASST$1
fi
